### ISSUE TITLE
Loader.php的一个小小问题

### ISSUE THREAD

**Issue by flydo** [flyhacker/cdvphp#1]
https://github.com/flyhacker/cdvphp/blob/master/CdvPHP/Loader/Loader.php#L64   

line: 64    

```
self::_checkClassName($class_name);    
```

> **这里调用了_checkClassName方法，但是返回值没有使用。   

https://github.com/flyhacker/cdvphp/blob/master/CdvPHP/Loader/Loader.php#L87  
line: 87~90   

```
    private static function _checkClassName($class_name)
    {/*{{{*/
        return (empty($class_name) || is_array($class_name));
    }/*}}}*/
```

**Comment by flyhacker** [comment]
fixed, thank you!
